language: csharp
mono: none
sudo: required
dist: focal
dotnet: 6.0.202
branches:
  only:
    - master
#    - develop
before_install:
  # Decrypt and add the Google Cloud SDK key
  - openssl aes-256-cbc -K $encrypted_your_encrypted_key -iv $encrypted_your_initialization_vector -in travis-net6-a23-c98189410a2b.json.enc -out travis-net6-a23-c98189410a2b.json -d

  # Add the Google Cloud SDK repository
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

  # Import the Google Cloud public key
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

  # Update the apt-get package list
  - sudo apt-get update

install:
  # Install the Google Cloud SDK
  - sudo apt-get install google-cloud-sdk
  
script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: travis-net6-a23-c98189410a2b.json
    project: tests-402501
    version: 1.0.1
    default: true
    on:
        all_branches: true
# [END travis_deploy]